apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openjdk-base-image-pipeline
spec:
  workspaces:
    - name: pipeline-workspace-tmp
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: private-registry-svc.default.svc.cluster.local:5000/openjdk11-base-image
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/intp-a/cicd-instances.git
        - name: revision
          value: "main"
        - name: deleteExisting
          value: "true"
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace-tmp
    - name: build-image
      runAfter:
        - clone-repository
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
        - name: DOCKERFILE
          value: ./cicd-instances/tekton/openjdk-base-image/dockerfile/Dockerfile.openjdk11
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-workspace-tmp
